# Generated by Django 5.2.6 on 2025-09-13 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sintoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('gravidade', models.IntegerField()),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('sintomas', models.ManyToManyField(to='app.sintoma')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
